<?php
    $quotes=[
        "Every small step forward brings you closer to your dreams.",
        "Your potential is limitless; dare to unleash it.",
        "Mistakes are proof that you're trying and learning.",
        "The only person you need to be better than is the one you were yesterday.",
        "You have the power to rewrite your story at any moment.",
        "Success is built on consistency, not perfection.",
        "Your greatest growth often comes from your greatest challenges.",
        "Dream big, but work bigger.",
        "Focus on progress, not perfection.",
        "Believe in yourself, even when no one else does.",
        "The journey matters just as much as the destination.",
        "Discomfort is the price of growth; embrace it.",
        "You are capable of more than you realize.",
        "Turn your 'I wish' into 'I will.'",
        "Your attitude determines your altitude.",
        "Great things never come from comfort zones.",
        "Be the energy you want to attract.",
        "Each day is a new chance to become your best self.",
        "The harder you work, the luckier you get.",
        "You are stronger than your excuses.",
        "Dreams don't work unless you do.",
        "Your effort today creates your success tomorrow.",
        "Be fearless in the pursuit of what sets your soul on fire.",
        "Growth begins where fear ends.",
        "You can’t control everything, but you can control your effort.",
        "Big journeys begin with a single courageous step.",
        "Success is the sum of small efforts repeated daily.",
        "Your vibe attracts your tribe; stay positive.",
        "What you focus on expands; focus on the good.",
        "Doubt kills more dreams than failure ever will.",
        "Action turns potential into reality.",
        "Nothing is impossible when you believe in yourself.",
        "Don't wait for opportunity; create it.",
        "Failure is a detour, not a dead-end.",
        "Stay committed to your goals but flexible in your methods.",
        "Your dreams are valid, no matter how big or small.",
        "You hold the pen to write your own story.",
        "With passion and perseverance, anything is achievable.",
        "Your mindset is the key to unlocking your potential.",
        "What you do today determines your tomorrow.",
        "Your limits exist only in your mind.",
        "Small actions compound into massive results.",
        "You are a masterpiece in progress.",
        "Challenges are opportunities in disguise.",
        "Celebrate progress, no matter how small.",
        "Your only limit is how far you're willing to go.",
        "Success starts with a decision to try.",
        "Let go of fear and embrace possibility.",
        "You can always start fresh, no matter the time or place.",
        "Be brave enough to start, even if you're scared.",
        "Every day is a chance to make a difference.",
        "Persistence outshines talent when talent doesn’t persist.",
        "You don’t have to be great to start, but you have to start to be great.",
        "Believe in the beauty of your dreams.",
        "Courage is the bridge between dreams and reality.",
        "Make every setback a setup for a comeback.",
        "What you think, you become; choose your thoughts wisely.",
        "The best way to predict the future is to create it.",
        "Your resilience defines your destiny.",
        "Success is a marathon, not a sprint; pace yourself.",
        "Progress over perfection, every single time.",
        "Shine so brightly that you inspire others to shine too.",
        "Every ending is a new beginning in disguise.",
        "Life rewards those who take action, not those who wait.",
        "Keep moving forward; even slow progress is progress.",
        "The more you believe in yourself, the more the world believes in you.",
        "Focus on the solution, not the problem.",
        "You are braver than you believe and stronger than you seem.",
        "Your dreams are worth every ounce of effort.",
        "Step into your fears and find your courage waiting.",
        "Hard work beats talent when talent doesn’t work hard.",
        "Success loves preparation and persistence.",
        "You’re closer to your goal than you think; keep going.",
        "Celebrate the small wins along the way.",
        "Turn your setbacks into stepping stones.",
        "Confidence comes from doing, not waiting.",
        "No storm lasts forever; the sun always returns.",
        "The world needs your unique light; don’t dim it.",
        "Wake up with determination; go to bed with satisfaction.",
        "Embrace failure as a stepping stone to success.",
        "Nothing worth having comes easy, but it’s always worth it.",
        "Believe in your ability to create a better future.",
        "When the going gets tough, the tough get going.",
        "You’re not a product of your circumstances but of your decisions.",
        "Strength grows in the moments when you feel like giving up.",
        "Don’t let doubt overshadow your dreams.",
        "Hustle beats talent when talent takes a break.",
        "A positive mind attracts positive outcomes.",
        "Your journey is unique, and that’s your power.",
        "The best time to start is now.",
        "Push through the pain to discover your strength.",
        "Dreams demand hustle; show them your grit.",
        "Your future self will thank you for the effort you put in today."
    ];
    $n=count($quotes)-1;
    echo $quotes[mt_rand(0,$n)];
?>